AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack completa: VPC pública + EC2 com SSH + deploy automático de API Nest.js via git clone"

Parameters:
  StackName:
    Type: String
    Description: Nome da Stack 
    Default: c171686a4454188l12585422t1w312162729893
    Id: arn:aws:cloudformation:us-east-1:312162729893:stack/c171686a4454188l12585422t1w312162729893/839ae510-c264-11f0-aa7e-12c75d78730d
  KeyName:
    Type: AWS::EC2::KeyPair::myKey
    Description: Nome do Key Pair existente para acesso SSH (EC2 → Key Pairs).
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t2.micro, t3.micro, t3.small, t3.medium]
    Description: Tipo da instância EC2.
  AllowedSSH:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR permitido para SSH (porta 22). Em produção, restrinja!
  AllowedHTTP:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR permitido para o serviço (porta 3000).
  GitRepoUrl:
    Type: String
    Default: "https://github.com/luivargas/projeto_devops_na_pratica"
    Description: URL do repositório GIT (público) da API Nest.js.
  GitBranch:
    Type: String
    Default: "main"
    Description: Branch a clonar.
  AppPort:
    Type: Number
    Default: 3000
    Description: Porta da API Nest.js.
  UsePm2:
    Type: String
    Default: "false"
    AllowedValues: ["true","false"]
    Description: Iniciar com PM2 (true) ou como serviço systemd (false).

Conditions:
  UsePM2: !Equals [!Ref UsePm2, "true"]

Resources:
  ########################################################
  # Rede: VPC mínima pública com Internet
  ########################################################
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: [{ Key: Name, Value: !Sub "${AWS::StackName}-vpc" }]

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: [{ Key: Name, Value: !Sub "${AWS::StackName}-igw" }]

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.10.1.0/24
      MapPublicIpOnLaunch: true
      Tags: [{ Key: Name, Value: !Sub "${AWS::StackName}-public-subnet" }]

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags: [{ Key: Name, Value: !Sub "${AWS::StackName}-rtb-public" }]

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  ########################################################
  # Segurança: SG com SSH (22) e App (AppPort)
  ########################################################
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Acesso SSH (22) e API (AppPort)"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: !Ref AllowedSSH }
        - { IpProtocol: tcp, FromPort: !Ref AppPort, ToPort: !Ref AppPort, CidrIp: !Ref AllowedHTTP }
      Tags: [{ Key: Name, Value: !Sub "${AWS::StackName}-sg" }]

  ########################################################
  # IAM: Role/InstanceProfile (SSM + ECR ReadOnly)
  ########################################################
  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags: [{ Key: Name, Value: !Sub "${AWS::StackName}-ec2-role" }]

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      PublicIP: 18.207.159.189
      InstanceId: i-059c34e734dd6d658
      Roles: [!Ref Ec2Role]
      InstanceProfileName: !Sub "${AWS::StackName}-ec2-profile"

  ########################################################
  # AMI mais recente (Amazon Linux 2023)
  ########################################################
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"

  ########################################################
  # EC2 + UserData: instala Node, clona repo, builda e sobe serviço
  ########################################################
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref Ec2InstanceProfile
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet
          GroupSet: [!Ref AppSecurityGroup]
      Tags:
        - { Key: Name, Value: !Sub "${AWS::StackName}-nestjs" }
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

          # Atualiza pacotes e instala dependências
          dnf -y update
          dnf -y install git nodejs npm

          # Instala PM2 se selecionado
          if [ "${UsePm2}" = "true" ]; then
            npm install -g pm2
          fi

          # Clona a aplicação
          mkdir -p /opt/app
          chown ec2-user:ec2-user /opt/app
          su - ec2-user -c "git clone --branch ${GitBranch} ${GitRepoUrl} /opt/app || (cd /opt/app && git pull)"

          # Instala e builda
          cd /opt/app
          su - ec2-user -c "cd /opt/app && npm ci || npm install"
          su - ec2-user -c "cd /opt/app && npm run build"

          # Cria serviço systemd (caso não use PM2)
          if [ "${UsePm2}" = "false" ]; then
            cat >/etc/systemd/system/nestjs.service <<SERVICE
          [Unit]
          Description=NestJS API
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/opt/app
          ExecStart=/usr/bin/npm run start:prod
          Restart=always
          RestartSec=5
          User=ec2-user
          Environment=NODE_ENV=production
          Environment=PORT=${AppPort}

          [Install]
          WantedBy=multi-user.target
          SERVICE

            systemctl daemon-reload
            systemctl enable nestjs
            systemctl start nestjs
          else
            # Inicia via PM2
            su - ec2-user -c "cd /opt/app && PORT=${AppPort} pm2 start dist/main.js --name nestjs || pm2 start npm --name nestjs -- run start:prod"
            su - ec2-user -c "pm2 save"
            # PM2 como serviço de inicialização
            env PATH=$PATH:/usr/bin su - ec2-user -c "pm2 startup systemd -u ec2-user --hp /home/ec2-user"
          fi

          echo "Setup concluído. API deve estar ouvindo na porta ${AppPort}."

Outputs:
  PublicIP:
    Description: IP público da instância
    Value: !GetAtt AppInstance.PublicIp
  PublicDNS:
    Description: DNS público da instância
    Value: !GetAtt AppInstance.PublicDnsName
  SSHCommandExample:
    Description: Exemplo de conexão SSH
    Value: !Sub "ssh -i /caminho/para/sua-chave.pem ec2-user@${AppInstance.PublicDnsName}"
  UrlExample:
    Description: URL de teste (HTTP direto na porta da app)
    Value: !Sub "http://${AppInstance.PublicDnsName}:${AppPort}"
