AWSTemplateFormatVersion: "2010-09-09"
Description: "Infra mínima para rodar uma API Nest.js."

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC onde a instância EC2 será criada.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Sub-rede pública onde a instância EC2 ficará.
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome do KeyPair para acesso SSH (crie em EC2 > Key Pairs).
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
    Description: Tipo da instância EC2 (t3.micro cobre o Free Tier em muitas contas).
  AllowedCidr:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR permitido para acesso à API (porta 3000) e SSH (22). Em produção, restrinja!
  CreateArtifactsBucket:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Cria um bucket S3 para artefatos/logs do pipeline? (true/false)

Mappings:
  # Usa a última AMI do Amazon Linux 2023 (x86_64) via SSM Parameter
  # Não é um mapping tradicional; pegaremos via SSM no Launch Properties.
  # Mantido aqui apenas para clareza da seção.

Conditions:
  ShouldCreateBucket: !Equals [!Ref CreateArtifactsBucket, "true"]

Resources:

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Acesso SSH (22) e API Nest (3000)"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCidr
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: !Ref AllowedCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"

  Ec2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        # Session Manager (acesso via console sem precisar abrir 22)
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        # (Opcional) Leitura de ECR caso usem imagens em deploy futuro
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ec2-role"

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref Ec2InstanceRole]
      InstanceProfileName: !Sub "${AWS::StackName}-ec2-profile"

  AppEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref Ec2InstanceProfile
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet: [!Ref AppSecurityGroup]
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-nestjs"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -eux

          # Atualiza pacotes
          dnf -y update

          # Instala Node.js e npm (Amazon Linux 2023)
          dnf -y install nodejs npm git

          # PM2 para gerenciar processos Node (opcional)
          npm install -g pm2

          # Placeholder de diretório da aplicação
          mkdir -p /opt/app
          chown ec2-user:ec2-user /opt/app

          # Cria um serviço systemd de exemplo (ajuste ExecStart conforme seu deploy)
          cat >/etc/systemd/system/nestjs.service <<'SERVICE'
          [Unit]
          Description=NestJS App
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/opt/app
          ExecStart=/usr/bin/node dist/main.js
          Restart=always
          RestartSec=5
          User=ec2-user
          Environment=NODE_ENV=production
          # Dica: seu pipeline pode enviar os arquivos para /opt/app e fazer npm ci && npm run build

          [Install]
          WantedBy=multi-user.target
          SERVICE

          systemctl daemon-reload
          # systemctl enable nestjs && systemctl start nestjs
          echo "Bootstrap OK - aguardando artefatos do pipeline para iniciar o serviço."

  ########################################################
  # SSM Parameter para obter AMI mais recente do AL2023
  ########################################################
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"

Outputs:
  InstanceId:
    Description: ID da instância EC2
    Value: !Ref AppEc2Instance
  PublicIP:
    Description: IP público da instância
    Value: !GetAtt AppEc2Instance.PublicIp
  PublicDNS:
    Description: DNS público da instância
    Value: !GetAtt AppEc2Instance.PublicDnsName
  SecurityGroupId:
    Description: ID do Security Group
    Value: !Ref AppSecurityGroup
  ArtifactsBucketName:
    Condition: ShouldCreateBucket
    Description: Nome do bucket S3 de artefatos
    Value: !Ref ArtifactsBucket
